# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FourBar_GUI.ui'
# Created by: PyQt5 UI code generator 5.15.7
# WARNING: Any manual changes made to this file will be lost when pyuic5 is run again.
# Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    """
    This class defines the GUI layout for the Four-Bar Linkage simulation application.
    It is auto-generated from the 'FourBar_GUI.ui' file using the PyQt5 UI compiler.

    Attributes:
        Widgets such as labels, spin boxes, and a QGraphicsView are defined and laid out
        using QVBoxLayout and QHBoxLayout to organize the user interface.
    """

    def setupUi(self, Form):
        """
        Set up all the UI components and layouts within the given Form.

        Args:
            Form (QWidget): The parent widget where all UI components will be placed.
        """
        Form.setObjectName("Form")
        Form.resize(1723, 1408)

        # Top-level vertical layout
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        # --- First Horizontal Layout (Zoom and Angle Inputs) --- #
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Zoom Label
        self.lbl_Zoom = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.lbl_Zoom.setSizePolicy(sizePolicy)
        self.lbl_Zoom.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_Zoom.setFont(font)
        self.lbl_Zoom.setObjectName("lbl_Zoom")
        self.horizontalLayout.addWidget(self.lbl_Zoom)

        # Zoom SpinBox
        self.spnd_Zoom = QtWidgets.QDoubleSpinBox(Form)
        self.spnd_Zoom.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spnd_Zoom.setFont(font)
        self.spnd_Zoom.setProperty("value", 1.0)
        self.spnd_Zoom.setObjectName("spnd_Zoom")
        self.horizontalLayout.addWidget(self.spnd_Zoom)

        # Spacer to push angle controls to the right
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        # Input Angle Label
        self.lbl_InputAngle = QtWidgets.QLabel(Form)
        self.lbl_InputAngle.setMaximumSize(QtCore.QSize(30, 16777215))
        font.setFamily("Symbol")
        self.lbl_InputAngle.setFont(font)
        self.lbl_InputAngle.setObjectName("lbl_InputAngle")
        self.horizontalLayout.addWidget(self.lbl_InputAngle)

        # Input Angle SpinBox
        self.nud_InputAngle = QtWidgets.QDoubleSpinBox(Form)
        self.nud_InputAngle.setMaximum(360.0)
        self.nud_InputAngle.setProperty("value", 90.0)
        self.nud_InputAngle.setObjectName("nud_InputAngle")
        self.horizontalLayout.addWidget(self.nud_InputAngle)

        # Output Angle Label
        self.lbl_OutputAngle = QtWidgets.QLabel(Form)
        self.lbl_OutputAngle.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lbl_OutputAngle.setFont(font)
        self.lbl_OutputAngle.setObjectName("lbl_OutputAngle")
        self.horizontalLayout.addWidget(self.lbl_OutputAngle)

        # Output Angle Value Display
        self.lbl_OutputAngle_Val = QtWidgets.QLabel(Form)
        self.lbl_OutputAngle_Val.setObjectName("lbl_OutputAngle_Val")
        self.horizontalLayout.addWidget(self.lbl_OutputAngle_Val)

        # Add the first row layout to the main vertical layout
        self.verticalLayout.addLayout(self.horizontalLayout)

        # --- Second Vertical Layout for Link Length Inputs --- #
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Horizontal layout for Link 1 Length
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.lbl_Link1Length = QtWidgets.QLabel(Form)
        self.lbl_Link1Length.setObjectName("lbl_Link1Length")
        self.horizontalLayout_4.addWidget(self.lbl_Link1Length)

        self.nud_Link1Length = QtWidgets.QDoubleSpinBox(Form)
        self.nud_Link1Length.setMaximum(5000.0)
        self.nud_Link1Length.setObjectName("nud_Link1Length")
        self.horizontalLayout_4.addWidget(self.nud_Link1Length)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        # Horizontal layout for Link 3 Length
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)

        self.nud_Link3Length = QtWidgets.QDoubleSpinBox(Form)
        self.nud_Link3Length.setMaximum(5000.0)
        self.nud_Link3Length.setObjectName("nud_Link3Length")
        self.horizontalLayout_3.addWidget(self.nud_Link3Length)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        # Add the second layout (link controls) to the main layout
        self.verticalLayout.addLayout(self.verticalLayout_2)

        # --- Graphics View for Drawing the Four-Bar Linkage --- #
        self.gv_Main = QtWidgets.QGraphicsView(Form)
        self.gv_Main.setMouseTracking(True)
        self.gv_Main.setObjectName("gv_Main")
        self.verticalLayout.addWidget(self.gv_Main)

        # Set default text for widgets
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        """
        Sets the text of the various labels. Called automatically after setupUi().

        Args:
            Form (QWidget): The parent form.
        """
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_Zoom.setText(_translate("Form", "Zoom"))
        self.lbl_InputAngle.setText(_translate("Form", "f1"))
        self.lbl_OutputAngle.setText(_translate("Form", "f3"))
        self.lbl_OutputAngle_Val.setText(_translate("Form", "0.00"))
        self.lbl_Link1Length.setText(_translate("Form", "Link 1 Length"))
        self.label_2.setText(_translate("Form", "Link 3 Length"))
